apiVersion: v1
kind: ReplicationController
metadata:
  name: demo
  labels:
    name: demo
spec:
  replicas: 3   #副本数为3，k8s会自动进行负载均衡
  selector:
    name: demo
  template:
    metadata:
      name: demo
      labels:
        name: demo
    spec:
      containers:
        - name: demo
          image: jiafeimaochaokeai/demo:v1.1
          imagePullPolicy: IfNotPresent    #镜像拉取策略
          ports:
            - containerPort: 8080
