apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
  labels:
    name: redis
spec:
  replicas: 1  #副本数为1
  selector:
    name: redis
  template:   #模板
    metadata:
      name: redis
      labels:
        name: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent  #镜像拉取策略
          ports:
            - containerPort: 6379   #容器端口